### ISSUE TITLE
Do you have visualize code for CBC?

### ISSUE THREAD

**Issue by KarlFreecss** [EmilioOldenziel/torch-cbc#1]
I have run your code, and the components do not look like a number as Keras code(https://github.com/saralajew/cbc_networks)?

I also tried to implement CBC in PyTorch, but it does not work too.
-------------------------------------------------------------------------
# My visualize code
    for idx, c in enumerate(model.components):
        prototype = c
        img = prototype.view(28, 28).cpu().data.numpy()
        img = img * 255
        img = cv.resize(img, (56, 56))                 
        cv.imwrite("char_img/%d.png" % idx, img)

**Comment by EmilioOldenziel** [comment]
Hi @KarlFreecss,
I am also struggling to get and visualize the nice backpropagated components.
So far I've discovered that I had to split the optimization of the backbone and the components, like is performed in GANs.
I also added the euclidean constraint to the convolutional kernels.
The results so far can be seen in the the Visualize_components notebook.

**Comment by KarlFreecss** [comment]
I am doing some experiment via your code, it has some exciting result now, but I need speed some time to check it. As soon as I locate the problem, I will share them with you.
